import { jsPDF } from 'jspdf';
import { formatNPR } from './parseCoords';
import { STATUS_LABELS } from './constants';

type ReportSection = { heading: string; body?: string; rows?: [string, string][] };

interface ReportOptions {
  title: string;
  subtitle?: string;
  sections: ReportSection[];
  filename: string;
}

const NAVY: [number, number, number] = [15, 27, 61];
const CRIMSON: [number, number, number] = [199, 36, 51];
const MUTED: [number, number, number] = [100, 110, 130];

export function generatePdfReport({ title, subtitle, sections, filename }: ReportOptions) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 48;
  const contentW = pageW - margin * 2;
  let y = margin;

  // Header band
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, pageW, 90, 'F');
  doc.setFillColor(...CRIMSON);
  doc.rect(0, 90, pageW, 4, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.text('NEPAL INFRA WATCH', margin, 36);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.text('Infrastructure Monitoring Report', margin, 50);
  doc.setFontSize(8);
  doc.text(new Date().toLocaleDateString(), pageW - margin, 36, { align: 'right' });

  y = 130;

  // Title
  doc.setTextColor(...NAVY);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  const titleLines = doc.splitTextToSize(title, contentW);
  doc.text(titleLines, margin, y);
  y += titleLines.length * 22;

  if (subtitle) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(...MUTED);
    const subLines = doc.splitTextToSize(subtitle, contentW);
    doc.text(subLines, margin, y);
    y += subLines.length * 13 + 6;
  }

  doc.setDrawColor(...CRIMSON);
  doc.setLineWidth(1.5);
  doc.line(margin, y, margin + 40, y);
  y += 18;

  const ensureSpace = (h: number) => {
    if (y + h > pageH - margin - 20) {
      doc.addPage();
      y = margin;
    }
  };

  const addFooter = () => {
    const pageNo = doc.getCurrentPageInfo().pageNumber;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text('Generated by Nepal Infra Watch · nepalinfrawatch.app', margin, pageH - 24);
    doc.text(`Page ${pageNo}`, pageW - margin, pageH - 24, { align: 'right' });
  };

  for (const section of sections) {
    ensureSpace(40);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(...CRIMSON);
    doc.text(section.heading.toUpperCase(), margin, y);
    y += 6;
    doc.setDrawColor(220, 220, 225);
    doc.setLineWidth(0.5);
    doc.line(margin, y, pageW - margin, y);
    y += 14;

    if (section.rows) {
      doc.setFontSize(9.5);
      for (const [k, v] of section.rows) {
        ensureSpace(18);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...NAVY);
        doc.text(k, margin, y);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(40, 40, 50);
        const valLines = doc.splitTextToSize(String(v ?? '—'), contentW - 140);
        doc.text(valLines, margin + 140, y);
        y += Math.max(14, valLines.length * 12) + 2;
      }
      y += 6;
    }

    if (section.body) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(40, 40, 50);
      const bodyLines = doc.splitTextToSize(section.body, contentW);
      for (const line of bodyLines) {
        ensureSpace(14);
        doc.text(line, margin, y);
        y += 13;
      }
      y += 10;
    }
  }

  // Stamp footers on every page in one pass to avoid double-printing.
  const totalPages = (doc.internal as any).getNumberOfPages();
  for (let pg = 1; pg <= totalPages; pg++) {
    doc.setPage(pg);
    addFooter();
  }
  doc.save(filename);
}

export function exportProjectReport(
  project: any,
  aiSummary: string,
  milestones: any[] = [],
  updates: any[] = [],
  narrativeSummary: string | null = null,
  gapsAndContradictions: string[] = [],
) {
  const sections: ReportSection[] = [
    {
      heading: 'Project overview',
      rows: [
        ['Sector', project.sector],
        ['Status', STATUS_LABELS[project.status] ?? project.status],
        ['Province', project.province ?? '—'],
        ['District', project.district ?? '—'],
        ['Budget', formatNPR(project.budget_npr)],
        ['Progress', `${project.progress_percent ?? 0}%`],
        ['Implementing agency', project.implementing_agency ?? '—'],
        ['Contractor', project.contractor ?? '—'],
        ['Timeline', `${project.start_date ?? 'TBD'} → ${project.expected_completion ?? 'TBD'}`],
      ],
    },
  ];
  if (project.description) sections.push({ heading: 'Description', body: project.description });
  if (aiSummary) sections.push({ heading: 'AI brief', body: aiSummary });
  // Narrative + gaps come from the latest project_analysis_runs row; they
  // belong in the same exported document as the brief so a downloaded PDF
  // captures the full AI-generated picture the user saw on screen.
  if (narrativeSummary) sections.push({ heading: 'AI synthesis', body: narrativeSummary });
  if (gapsAndContradictions.length > 0) {
    sections.push({
      heading: 'Gaps & contradictions',
      body: gapsAndContradictions.map(g => `• ${g}`).join('\n'),
    });
  }
  if (milestones.length) {
    sections.push({
      heading: 'Milestones',
      body: milestones.map(m => `• ${m.title} [${m.status}] — due ${m.due_date ?? '—'}${m.description ? `\n  ${m.description}` : ''}`).join('\n'),
    });
  }
  if (updates.length) {
    sections.push({
      heading: 'Recent updates',
      body: updates.slice(0, 8).map(u => `• ${new Date(u.created_at).toLocaleDateString()} — ${u.title}\n  ${u.content ?? ''}`).join('\n\n'),
    });
  }

  generatePdfReport({
    title: project.title,
    subtitle: `${project.sector} · ${project.district ?? ''}${project.province ? `, ${project.province}` : ''}`,
    sections,
    filename: `${(project.slug ?? 'project')}-report.pdf`,
  });
}

export function exportComparisonReport(projects: any[], aiText: string) {
  const sections: ReportSection[] = [
    {
      heading: 'Projects compared',
      body: projects.map((p, i) => `${i + 1}. ${p.title} — ${p.sector}, ${formatNPR(p.budget_npr)}`).join('\n'),
    },
  ];

  const fields: [string, (p: any) => string][] = [
    ['Status', p => STATUS_LABELS[p.status] ?? p.status],
    ['Sector', p => p.sector],
    ['Province', p => p.province ?? '—'],
    ['District', p => p.district ?? '—'],
    ['Budget', p => formatNPR(p.budget_npr)],
    ['Progress', p => `${p.progress_percent ?? 0}%`],
    ['Contractor', p => p.contractor ?? '—'],
    ['Agency', p => p.implementing_agency ?? '—'],
    ['Start', p => p.start_date ?? '—'],
    ['Completion', p => p.expected_completion ?? '—'],
  ];

  for (const p of projects) {
    sections.push({
      heading: p.title,
      rows: fields.map(([label, fn]) => [label, fn(p)] as [string, string]),
    });
  }

  if (aiText) sections.push({ heading: 'AI comparison insight', body: aiText });

  generatePdfReport({
    title: 'Project comparison report',
    subtitle: `${projects.length} projects · Generated ${new Date().toLocaleDateString()}`,
    sections,
    filename: `infra-comparison-${Date.now()}.pdf`,
  });
}
